#!/bin/bash

set -euo pipefail

#usage
usage() {
printf "\033[1;36m"
cat << 'EOF'
                     .-'`-.
                    / | |  \
                   /  | |   \
                  |___|_|__  |
                  ||<o>| <o>`|
                  ||   J_   )|
                  `|`-'__`-'|/
                   |  `--'  |
                 .-|        |_
              .-'  \     /  | |`-.
           .-'      `.     /| |   \
          /           ````' | |    \
         |_____             | |     L
      .-' ___   `-.         F F  |  |
    .'.-'  |  `-.  `.      J J   /  |
   / /|    |    |`.  \     | |   |/ |
  / / |    |    |  `. `.   F F   |  |
 J /  |    |    |    \  L J J    |  |
 FJ   |    |    |    |L J/ /     |   \
J |() | () | () | () | J L/      |   |
| F   | .-'_ \  |    |  LJ       | /  L
| L   | /    \\ |    |  | L      |    |
| L   ||     ):||    |  | |     /|     L
J |   ||:._.'::||    |  | |----' |     |
J |   |J:::::::||    |  | |    _/\     |
 LJ   | \:::::/ |    |  | |---'\  |    |
 J L  |  `-:-'  |    |  | F  | \  |    J
  LJ()| () | () | () |  F F  |  \  \--._L
   \ \|    |    |    | / /    |     |  |
    \ \    |    |    |/ /|     |    | .-'|
     `.`.  |    |   .'.' |     |    |/ /`L
EOF
printf "\033[0m"

printf "\033[1;31m"
cat << 'EOF'
	   _   ___ _  _ _____ ___  ___
	  /_\ | _ \ \| |_   _/ _ \| _ \
	 / _ \|   / .` | | || (_) |   /
	/_/ \_\_|_\_|\_| |_| \___/|_|_\
EOF
printf "\033[0m"
    echo ""
    echo "Arntor - STR genomic region classifier"
    echo ""
    echo "Developed by"
    echo "Furkan Çorapçı | Yandım LAB"
    echo ""
    echo "Usage:"
    echo "  $0 <annotation.gtf> <trf.tsv> <chrom.sizes> <prefix> <upstream> <downstream>"
    echo ""
}

# Help flag
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [ $# -eq 0 ]; then
    usage
    exit 0
fi

if [ $# -ne 6 ]; then
    echo "Error: Wrong number of arguments."
    usage
    exit 1
fi

#argument
annot=$1
trf=$2
chrom_sizes=$3
prefix=$4
upstream=$5
downstream=$6

#check
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

#region extracter
awk '$3=="gene"' "$annot" > ${prefix}_gene.gtf
awk '$3=="exon"' "$annot" > ${prefix}_exon.gtf

awk 'BEGIN{OFS="\t"} {print $1,$4-1,$5,"gene",".",$7}' \
    ${prefix}_gene.gtf > ${prefix}_genes.bed

awk 'BEGIN{OFS="\t"} {print $1,$4-1,$5,"exon",".",$7}' \
    ${prefix}_exon.gtf > ${prefix}_exons.bed

awk 'BEGIN{OFS="\t"}
{
    if($6=="+")
        print $1,$2,$2+1,$4,".",$6
    else
        print $1,$3-1,$3,$4,".",$6
}' ${prefix}_genes.bed > ${prefix}_tss.bed

bedtools slop -s -i ${prefix}_tss.bed -g "$chrom_sizes" \
    -l "$upstream" -r "$downstream" > ${prefix}_promoters.bed

bedtools sort -i ${prefix}_exons.bed | \
bedtools merge -s -c 4,6 -o distinct,distinct \
> ${prefix}_exons_merge.bed

bedtools sort -i ${prefix}_genes.bed | \
bedtools merge -s -c 4,6 -o distinct,distinct \
> ${prefix}_genes_merge.bed

bedtools sort -i ${prefix}_promoters.bed | \
bedtools merge -s -c 4,6 -o distinct,distinct \
> ${prefix}_promoters_merge.bed

bedtools subtract -s \
    -a ${prefix}_genes_merge.bed \
    -b ${prefix}_exons_merge.bed \
> ${prefix}_introns_merge.bed

#str prep
sort -k1,1 -k2,2n "$trf" > ${prefix}_trf.sorted.tsv

awk 'BEGIN{OFS="\t"} {print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11}' \
    ${prefix}_trf.sorted.tsv > ${prefix}_trf.bed

# intersect=
bedtools intersect -a ${prefix}_trf.bed \
-b ${prefix}_promoters_merge.bed -wa -u \
> ${prefix}_STR_promoter.bed

bedtools intersect -a ${prefix}_trf.bed \
-b ${prefix}_promoters_merge.bed -wa -v \
> ${prefix}_STR_non_promoter.bed

bedtools intersect -a ${prefix}_STR_non_promoter.bed \
-b ${prefix}_exons_merge.bed -wa -u \
> ${prefix}_STR_exon.bed

bedtools intersect -a ${prefix}_STR_non_promoter.bed \
-b ${prefix}_exons_merge.bed -wa -v \
> ${prefix}_STR_non_exon.bed

bedtools intersect -a ${prefix}_STR_non_exon.bed \
-b ${prefix}_introns_merge.bed -wa -u \
> ${prefix}_STR_intron.bed

bedtools intersect -a ${prefix}_STR_non_exon.bed \
-b ${prefix}_introns_merge.bed -wa -v \
> ${prefix}_STR_intergenic.bed

# overlap bp
bedtools intersect -a ${prefix}_STR_promoter.bed \
-b ${prefix}_promoters_merge.bed -wo \
> ${prefix}_final_promoter_bp.bed

bedtools intersect -a ${prefix}_STR_exon.bed \
-b ${prefix}_exons_merge.bed -wo \
> ${prefix}_final_exon_bp.bed

bedtools intersect -a ${prefix}_STR_intron.bed \
-b ${prefix}_introns_merge.bed -wo \
> ${prefix}_final_intron_bp.bed

echo "Arntor finished successfully."
